# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Diary(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, name: str=None, user_id: int=None):  # noqa: E501
        """Diary - a model defined in Swagger

        :param id: The id of this Diary.  # noqa: E501
        :type id: int
        :param name: The name of this Diary.  # noqa: E501
        :type name: str
        :param user_id: The user_id of this Diary.  # noqa: E501
        :type user_id: int
        """
        self.swagger_types = {
            'id': int,
            'name': str,
            'user_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'user_id': 'user_id'
        }
        self._id = id
        self._name = name
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'Diary':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Diary of this Diary.  # noqa: E501
        :rtype: Diary
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Diary.


        :return: The id of this Diary.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Diary.


        :param id: The id of this Diary.
        :type id: int
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Diary.


        :return: The name of this Diary.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Diary.


        :param name: The name of this Diary.
        :type name: str
        """

        self._name = name

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Diary.


        :return: The user_id of this Diary.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Diary.


        :param user_id: The user_id of this Diary.
        :type user_id: int
        """

        self._user_id = user_id
