# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Note(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, data: str=None, _date: date=None, user_id: int=None):  # noqa: E501
        """Note - a model defined in Swagger

        :param id: The id of this Note.  # noqa: E501
        :type id: int
        :param data: The data of this Note.  # noqa: E501
        :type data: str
        :param _date: The _date of this Note.  # noqa: E501
        :type _date: date
        :param user_id: The user_id of this Note.  # noqa: E501
        :type user_id: int
        """
        self.swagger_types = {
            'id': int,
            'data': str,
            '_date': date,
            'user_id': int
        }

        self.attribute_map = {
            'id': 'id',
            'data': 'data',
            '_date': 'date',
            'user_id': 'user_id'
        }
        self._id = id
        self._data = data
        self.__date = _date
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'Note':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Note of this Note.  # noqa: E501
        :rtype: Note
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Note.


        :return: The id of this Note.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Note.


        :param id: The id of this Note.
        :type id: int
        """

        self._id = id

    @property
    def data(self) -> str:
        """Gets the data of this Note.


        :return: The data of this Note.
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data: str):
        """Sets the data of this Note.


        :param data: The data of this Note.
        :type data: str
        """

        self._data = data

    @property
    def _date(self) -> date:
        """Gets the _date of this Note.


        :return: The _date of this Note.
        :rtype: date
        """
        return self.__date

    @_date.setter
    def _date(self, _date: date):
        """Sets the _date of this Note.


        :param _date: The _date of this Note.
        :type _date: date
        """

        self.__date = _date

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Note.


        :return: The user_id of this Note.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Note.


        :param user_id: The user_id of this Note.
        :type user_id: int
        """

        self._user_id = user_id
