# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ViewsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, user_id: int=None, note_id: int=None, quantity: int=None):  # noqa: E501
        """ViewsBody - a model defined in Swagger

        :param user_id: The user_id of this ViewsBody.  # noqa: E501
        :type user_id: int
        :param note_id: The note_id of this ViewsBody.  # noqa: E501
        :type note_id: int
        :param quantity: The quantity of this ViewsBody.  # noqa: E501
        :type quantity: int
        """
        self.swagger_types = {
            'user_id': int,
            'note_id': int,
            'quantity': int
        }

        self.attribute_map = {
            'user_id': 'userId',
            'note_id': 'note_id',
            'quantity': 'quantity'
        }
        self._user_id = user_id
        self._note_id = note_id
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'ViewsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The views_body of this ViewsBody.  # noqa: E501
        :rtype: ViewsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def user_id(self) -> int:
        """Gets the user_id of this ViewsBody.


        :return: The user_id of this ViewsBody.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this ViewsBody.


        :param user_id: The user_id of this ViewsBody.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def note_id(self) -> int:
        """Gets the note_id of this ViewsBody.


        :return: The note_id of this ViewsBody.
        :rtype: int
        """
        return self._note_id

    @note_id.setter
    def note_id(self, note_id: int):
        """Sets the note_id of this ViewsBody.


        :param note_id: The note_id of this ViewsBody.
        :type note_id: int
        """

        self._note_id = note_id

    @property
    def quantity(self) -> int:
        """Gets the quantity of this ViewsBody.


        :return: The quantity of this ViewsBody.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: int):
        """Sets the quantity of this ViewsBody.


        :param quantity: The quantity of this ViewsBody.
        :type quantity: int
        """

        self._quantity = quantity
